# Spring Boot configuration
spring:
# Database
  datasource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/crud
    username: namhd94
    password: 
# JPA properties
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true